import { useCallback, useEffect, useState } from 'react';
import { FileText, Save } from 'lucide-react';
import { Button } from '@shared/components/ui/button';
import { Input } from '@shared/components/ui/input';
import { Label } from '@shared/components/ui/label';
import { useLanguage } from '@shared/context/LanguageContext';
import { settingsAPI } from '@shared/services/api';
import { toast } from 'sonner';

type ReportTemplateType = 'violation_summary' | 'fine_summary' | 'detection_summary';

type TemplateFields = {
  title: string;
  header_text: string;
  footer_text: string;
};

const SETTINGS_KEY = 'report_templates';

const DEFAULT_TEMPLATES: Record<ReportTemplateType, TemplateFields> = {
  violation_summary: {
    title: 'Violation Summary Report',
    header_text: 'CamTraffic — Traffic Violation Summary',
    footer_text: 'Generated by CamTraffic enforcement system. Confidential.',
  },
  fine_summary: {
    title: 'Fine Summary Report',
    header_text: 'CamTraffic — Fine Collection Summary',
    footer_text: 'All amounts in KHR unless stated otherwise.',
  },
  detection_summary: {
    title: 'Detection Summary Report',
    header_text: 'CamTraffic — AI Detection Summary',
    footer_text: 'Detection metrics are approximate and subject to review.',
  },
};

const TYPES: ReportTemplateType[] = ['violation_summary', 'fine_summary', 'detection_summary'];

const TYPE_LABELS: Record<ReportTemplateType, { key: string; fallback: string }> = {
  violation_summary: { key: 'reportTemplates.typeViolation', fallback: 'Violation summary' },
  fine_summary: { key: 'reportTemplates.typeFine', fallback: 'Fine summary' },
  detection_summary: { key: 'reportTemplates.typeDetection', fallback: 'Detection summary' },
};

function mergeTemplates(value: unknown): Record<ReportTemplateType, TemplateFields> {
  const base = { ...DEFAULT_TEMPLATES };
  if (!value || typeof value !== 'object') return base;
  const parsed = value as Partial<Record<ReportTemplateType, Partial<TemplateFields>>>;
  for (const type of TYPES) {
    if (parsed[type]) {
      base[type] = { ...base[type], ...parsed[type] };
    }
  }
  return base;
}

export function ReportTemplatesManagementPanel() {
  const { t } = useLanguage();
  const tr = (key: string, fallback: string) => {
    const v = t(key);
    return v !== key ? v : fallback;
  };

  const [templates, setTemplates] = useState(DEFAULT_TEMPLATES);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await settingsAPI.get(SETTINGS_KEY);
      setTemplates(mergeTemplates(res.value));
    } catch {
      setTemplates({ ...DEFAULT_TEMPLATES });
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { void load(); }, [load]);

  const updateField = useCallback(
    (type: ReportTemplateType, field: keyof TemplateFields, value: string) => {
      setTemplates((prev) => ({
        ...prev,
        [type]: { ...prev[type], [field]: value },
      }));
    },
    [],
  );

  const handleSave = async () => {
    setSaving(true);
    try {
      await settingsAPI.save(SETTINGS_KEY, templates, 'Report PDF templates');
      toast.success(tr('reportTemplates.saved', 'Report templates saved'));
    } catch {
      try {
        await settingsAPI.update(SETTINGS_KEY, templates);
        toast.success(tr('reportTemplates.saved', 'Report templates saved'));
      } catch {
        toast.error(tr('reportTemplates.saveFailed', 'Failed to save report templates'));
      }
    } finally {
      setSaving(false);
    }
  };

  return (
    <section className="enforcement-page__panel p-5 mt-6">
      <div className="flex items-center justify-between gap-3 flex-wrap mb-4">
        <div className="flex items-center gap-2">
          <FileText size={18} className="text-blue-600" />
          <h2 className="font-semibold text-lg">{tr('reportTemplates.title', 'Report templates')}</h2>
        </div>
        <Button type="button" size="sm" onClick={() => void handleSave()} disabled={saving || loading}>
          <Save size={14} className="mr-1.5" />
          {tr('reportTemplates.save', 'Save templates')}
        </Button>
      </div>
      <p className="text-sm text-muted-foreground mb-4">
        {tr('reportTemplates.hint', 'Customize PDF report headers and footers. Use placeholders like {date}, {plate}, {amount}.')}
      </p>
      {loading ? (
        <p className="text-sm text-muted-foreground">{tr('common.loading', 'Loading…')}</p>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4">
          {TYPES.map((type) => {
            const label = TYPE_LABELS[type];
            return (
              <div key={type} className="rounded-xl border border-slate-200 dark:border-slate-700 p-4 space-y-3">
                <p className="text-sm font-semibold">{tr(label.key, label.fallback)}</p>
                <div>
                  <Label htmlFor={`rpt-title-${type}`}>{tr('reportTemplates.titleField', 'Title')}</Label>
                  <Input
                    id={`rpt-title-${type}`}
                    value={templates[type].title}
                    onChange={(e) => updateField(type, 'title', e.target.value)}
                    className="mt-1"
                  />
                </div>
                <div>
                  <Label htmlFor={`rpt-header-${type}`}>{tr('reportTemplates.header', 'Header text')}</Label>
                  <textarea
                    id={`rpt-header-${type}`}
                    value={templates[type].header_text}
                    onChange={(e) => updateField(type, 'header_text', e.target.value)}
                    rows={2}
                    className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                  />
                </div>
                <div>
                  <Label htmlFor={`rpt-footer-${type}`}>{tr('reportTemplates.footer', 'Footer text')}</Label>
                  <textarea
                    id={`rpt-footer-${type}`}
                    value={templates[type].footer_text}
                    onChange={(e) => updateField(type, 'footer_text', e.target.value)}
                    rows={2}
                    className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                  />
                </div>
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}
