# Generated by Django 4.2.30 on 2026-06-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_camera_frame_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='detection_count_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='resolution',
            field=models.CharField(blank=True, help_text='e.g. 1080p', max_length=10),
        ),
        migrations.AlterField(
            model_name='camera',
            name='frame_source_url',
            field=models.URLField(blank=True, help_text='RTSP or HTTPS stream/snapshot URL', max_length=500),
        ),
    ]
