# Generated by Django 4.2.30 on 2026-06-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_foundation_prd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('ptz', 'PTZ'), ('mobile', 'Mobile'), ('speed', 'Speed')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='frame_source_url',
            field=models.URLField(blank=True, help_text='RTSP or HTTPS stream/snapshot URL (PRD: stream_url)', max_length=500),
        ),
        migrations.AlterField(
            model_name='camera',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='road',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='trafficsignal',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trafficsignal',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['road', 'status'], name='idx_camera_road_status'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['status', '-last_ping'], name='idx_camera_status_ping'),
        ),
        migrations.AddIndex(
            model_name='road',
            index=models.Index(fields=['status', 'city'], name='idx_road_status_city'),
        ),
    ]
