# Generated by Django 4.2.30 on 2026-07-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0005_phase4_officers_stations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="frame_source_url",
            field=models.CharField(
                blank=True,
                help_text="RTSP or HTTPS stream/snapshot URL (PRD: stream_url)",
                max_length=500,
            ),
        ),
    ]
