# Generated by Django 6.0.7 on 2026-07-26 19:36
# Production Postgres already had several of these columns (schema drift);
# database_operations are idempotent so migrate works on both fresh and drifted DBs.

from django.db import migrations, models


_STATE_OPS = [
    migrations.AddField(
        model_name="road",
        name="commune",
        field=models.CharField(blank=True, default="", max_length=100),
    ),
    migrations.AddField(
        model_name="road",
        name="country",
        field=models.CharField(blank=True, default="Cambodia", max_length=100),
    ),
    migrations.AddField(
        model_name="road",
        name="deleted_at",
        field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="road",
        name="description",
        field=models.TextField(blank=True, default=""),
    ),
    migrations.AddField(
        model_name="road",
        name="direction",
        field=models.CharField(blank=True, default="", max_length=50),
    ),
    migrations.AddField(
        model_name="road",
        name="district",
        field=models.CharField(blank=True, default="", max_length=100),
    ),
    migrations.AddField(
        model_name="road",
        name="end_latitude",
        field=models.DecimalField(
            blank=True, decimal_places=7, max_digits=10, null=True
        ),
    ),
    migrations.AddField(
        model_name="road",
        name="end_longitude",
        field=models.DecimalField(
            blank=True, decimal_places=7, max_digits=10, null=True
        ),
    ),
    migrations.AddField(
        model_name="road",
        name="is_deleted",
        field=models.BooleanField(default=False),
    ),
    migrations.AddField(
        model_name="road",
        name="lanes",
        field=models.PositiveSmallIntegerField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="road",
        name="province",
        field=models.CharField(blank=True, default="", max_length=100),
    ),
    migrations.AddField(
        model_name="road",
        name="road_code",
        field=models.CharField(blank=True, default="", max_length=50),
    ),
    migrations.AddField(
        model_name="road",
        name="start_latitude",
        field=models.DecimalField(
            blank=True, decimal_places=7, max_digits=10, null=True
        ),
    ),
    migrations.AddField(
        model_name="road",
        name="start_longitude",
        field=models.DecimalField(
            blank=True, decimal_places=7, max_digits=10, null=True
        ),
    ),
    migrations.AddField(
        model_name="road",
        name="village",
        field=models.CharField(blank=True, default="", max_length=100),
    ),
    migrations.AlterField(
        model_name="camera",
        name="frame_source_url",
        field=models.CharField(
            blank=True,
            default="",
            help_text="Preferred snapshot/stream URL (HTTP JPEG, RTSP, or /media/cctv/…)",
            max_length=500,
        ),
    ),
    migrations.AlterField(
        model_name="road",
        name="city",
        field=models.CharField(blank=True, default="", max_length=100),
    ),
    migrations.AlterField(
        model_name="road",
        name="region",
        field=models.CharField(blank=True, default="", max_length=100),
    ),
]


def _existing_columns(schema_editor, table: str) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = current_schema() AND table_name = %s
                """,
                [table],
            )
            return {row[0] for row in cursor.fetchall()}
        if connection.vendor == "sqlite":
            cursor.execute(f"PRAGMA table_info({table})")  # noqa: S608 — fixed table
            return {row[1] for row in cursor.fetchall()}
    return set()


def apply_road_extended_fields(apps, schema_editor):
    """Add only missing Road columns (production may already have them)."""
    existing = _existing_columns(schema_editor, "roads")
    # (column, SQL fragment after ADD COLUMN)
    columns = [
        ("commune", "commune varchar(100) DEFAULT '' NOT NULL"),
        ("country", "country varchar(100) DEFAULT 'Cambodia' NOT NULL"),
        ("deleted_at", "deleted_at timestamp with time zone NULL"),
        ("description", "description text DEFAULT '' NOT NULL"),
        ("direction", "direction varchar(50) DEFAULT '' NOT NULL"),
        ("district", "district varchar(100) DEFAULT '' NOT NULL"),
        ("end_latitude", "end_latitude numeric(10, 7) NULL"),
        ("end_longitude", "end_longitude numeric(10, 7) NULL"),
        ("is_deleted", "is_deleted boolean DEFAULT false NOT NULL"),
        ("lanes", "lanes smallint NULL CHECK (lanes >= 0)"),
        ("province", "province varchar(100) DEFAULT '' NOT NULL"),
        ("road_code", "road_code varchar(50) DEFAULT '' NOT NULL"),
        ("start_latitude", "start_latitude numeric(10, 7) NULL"),
        ("start_longitude", "start_longitude numeric(10, 7) NULL"),
        ("village", "village varchar(100) DEFAULT '' NOT NULL"),
    ]
    # SQLite uses slightly different types — fall back to schema_editor for non-Postgres.
    if schema_editor.connection.vendor != "postgresql":
        Road = apps.get_model("infrastructure", "Road")
        # Fresh SQLite test DBs: apply via Django's AddField semantics through state only
        # is not enough — recreate with schema_editor.add_field for missing ones.
        from django.db import models as dj_models

        field_map = {
            "commune": dj_models.CharField(blank=True, default="", max_length=100),
            "country": dj_models.CharField(blank=True, default="Cambodia", max_length=100),
            "deleted_at": dj_models.DateTimeField(blank=True, null=True),
            "description": dj_models.TextField(blank=True, default=""),
            "direction": dj_models.CharField(blank=True, default="", max_length=50),
            "district": dj_models.CharField(blank=True, default="", max_length=100),
            "end_latitude": dj_models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
            "end_longitude": dj_models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
            "is_deleted": dj_models.BooleanField(default=False),
            "lanes": dj_models.PositiveSmallIntegerField(blank=True, null=True),
            "province": dj_models.CharField(blank=True, default="", max_length=100),
            "road_code": dj_models.CharField(blank=True, default="", max_length=50),
            "start_latitude": dj_models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
            "start_longitude": dj_models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
            "village": dj_models.CharField(blank=True, default="", max_length=100),
        }
        for name, field in field_map.items():
            if name in existing:
                continue
            field.set_attributes_from_name(name)
            schema_editor.add_field(Road, field)
        return

    with schema_editor.connection.cursor() as cursor:
        for name, ddl in columns:
            if name in existing:
                continue
            cursor.execute(f"ALTER TABLE roads ADD COLUMN {ddl}")  # noqa: S608 — fixed allowlist


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0007_camera_production_cctv_fields"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=_STATE_OPS,
            database_operations=[
                migrations.RunPython(apply_road_extended_fields, noop_reverse),
            ],
        ),
    ]
