# Generated by Django 5.1.7 on 2026-07-06 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cameras", "0001_initial"),
        ("detections", "0001_initial"),
        ("traffic_signs", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("appealed", "Appealed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "evidence_image",
                    models.ImageField(blank=True, null=True, upload_to="violations/"),
                ),
                ("detected_at", models.DateTimeField()),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("officer_notes", models.TextField(blank=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="violations",
                        to="cameras.camera",
                    ),
                ),
                (
                    "detection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="violation",
                        to="detections.detection",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "traffic_sign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="violations",
                        to="traffic_signs.trafficsign",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="violations",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "violations_violation",
                "ordering": ["-detected_at"],
            },
        ),
    ]
