# Generated by Django 6.0.7 on 2026-07-27 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_detection", "0009_drop_orphan_pedestrian_columns"),
        ("unknown_vehicles", "0002_uuid_schema_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="unknownvehicle",
            name="ai_detection_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unknown_vehicle_sightings",
                to="ai_detection.aidetectionlog",
            ),
        ),
        migrations.AddField(
            model_name="unknownvehicle",
            name="detected_class_key",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="unknownvehicle",
            name="observed_action",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
