# Generated by Django 4.2.13 on 2026-05-27 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('road_type', models.CharField(choices=[('highway', 'Highway'), ('urban', 'Urban'), ('rural', 'Rural'), ('intersection', 'Intersection')], default='urban', max_length=30)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('speed_limit', models.PositiveIntegerField(default=60)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roads',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_code', models.CharField(max_length=50)),
                ('cycle_duration', models.PositiveIntegerField(default=120, help_text='Seconds')),
                ('timing_sequence', models.JSONField(blank=True, default=dict)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traffic_signals', to='infrastructure.road')),
            ],
            options={
                'db_table': 'traffic_signals',
                'ordering': ['road', 'signal_code'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('camera_type', models.CharField(choices=[('fixed', 'Fixed'), ('ptz', 'PTZ'), ('speed', 'Speed')], default='fixed', max_length=30)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='infrastructure.road')),
            ],
            options={
                'db_table': 'cameras',
                'ordering': ['road', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='trafficsignal',
            constraint=models.UniqueConstraint(fields=('road', 'signal_code'), name='uniq_road_signal_code'),
        ),
    ]
