# Generated by Django 4.2.13 on 2026-06-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='frame_source_url',
            field=models.URLField(blank=True, help_text='Optional HTTP URL for live/snapshot frame preview (FE-08)', max_length=500),
        ),
        migrations.AddField(
            model_name='camera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
