# Generated by Django 4.2.13 on 2026-05-18 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidetectionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
