# Generated by Django 4.2.30 on 2026-07-25 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0007_camera_production_cctv_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_detection", "0009_drop_orphan_pedestrian_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload Video"),
                            ("live", "Live Camera"),
                            ("webcam", "Browser Webcam"),
                            ("simulation", "Local Simulation"),
                        ],
                        default="upload",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("streaming", "Streaming"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "original_video",
                    models.FileField(
                        blank=True, null=True, upload_to="ai/video/original/"
                    ),
                ),
                (
                    "annotated_video",
                    models.FileField(
                        blank=True, null=True, upload_to="ai/video/annotated/"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "model_name",
                    models.CharField(blank=True, default="YOLOv8", max_length=80),
                ),
                ("model_version", models.CharField(blank=True, max_length=80)),
                ("fps_original", models.FloatField(default=0.0)),
                ("fps_process", models.FloatField(default=0.0)),
                ("total_frames", models.PositiveIntegerField(default=0)),
                ("processed_frames", models.PositiveIntegerField(default=0)),
                ("current_frame", models.PositiveIntegerField(default=0)),
                ("detection_count", models.PositiveIntegerField(default=0)),
                ("vehicle_count", models.PositiveIntegerField(default=0)),
                ("sign_count", models.PositiveIntegerField(default=0)),
                ("plate_count", models.PositiveIntegerField(default=0)),
                ("plate_text", models.CharField(blank=True, max_length=40)),
                ("plate_confidence", models.FloatField(default=0.0)),
                ("avg_confidence", models.FloatField(default=0.0)),
                ("processing_time_sec", models.FloatField(default=0.0)),
                ("detection_json", models.JSONField(blank=True, default=dict)),
                ("violation_suggestion", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("observed_action", models.CharField(blank=True, max_length=50)),
                ("is_recording", models.BooleanField(default=False)),
                (
                    "ai_detection_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_detections",
                        to="ai_detection.aidetectionlog",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_detections",
                        to="infrastructure.camera",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "video_detections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoFrame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("frame_index", models.PositiveIntegerField()),
                ("timestamp_sec", models.FloatField(default=0.0)),
                (
                    "annotated_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="ai/video/frames/"
                    ),
                ),
                ("detections_json", models.JSONField(blank=True, default=dict)),
                ("sign_count", models.PositiveIntegerField(default=0)),
                ("vehicle_count", models.PositiveIntegerField(default=0)),
                ("plate_text", models.CharField(blank=True, max_length=40)),
                ("plate_confidence", models.FloatField(default=0.0)),
                ("confidence", models.FloatField(default=0.0)),
                ("processing_ms", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video_detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="ai_detection.videodetection",
                    ),
                ),
            ],
            options={
                "db_table": "video_frames",
                "ordering": ["frame_index"],
            },
        ),
        migrations.CreateModel(
            name="VideoEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("original_video", "Original Video"),
                            ("annotated_video", "Annotated Video"),
                            ("frame", "Frame Image"),
                            ("plate_crop", "Plate Crop"),
                            ("json", "Detection JSON"),
                            ("csv", "CSV Report"),
                            ("pdf", "PDF Report"),
                            ("recording", "Live Recording"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="ai/video/evidence/"
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=200)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video_detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="ai_detection.videodetection",
                    ),
                ),
            ],
            options={
                "db_table": "video_evidence",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="videoframe",
            constraint=models.UniqueConstraint(
                fields=("video_detection", "frame_index"), name="uniq_video_frame_index"
            ),
        ),
        migrations.AddIndex(
            model_name="videodetection",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_videodet_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="videodetection",
            index=models.Index(fields=["status"], name="idx_videodet_status"),
        ),
    ]
