# Generated by Django 5.1.7 on 2026-07-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("violations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("currency", models.CharField(default="KHR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                (
                    "violation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fine",
                        to="violations.violation",
                    ),
                ),
            ],
            options={
                "db_table": "fines_fine",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank Transfer"),
                            ("mobile", "Mobile Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("paid_at", models.DateTimeField()),
                (
                    "fine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="fines.fine",
                    ),
                ),
            ],
            options={
                "db_table": "fines_payment",
                "ordering": ["-paid_at"],
            },
        ),
    ]
