# Generated by Django 4.2.13 on 2026-05-18 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='fines/evidence/')),
                ('location', models.CharField(max_length=255)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fines',
                'ordering': ['-created_at'],
            },
        ),
    ]
