# Generated by Django 4.2.30 on 2026-06-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0003_fine_due_date_fine_payment_method_fine_violation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='officer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fine',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='fines/payments/'),
        ),
        migrations.AddField(
            model_name='fine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('disputed', 'Disputed'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
    ]
