# Generated by Django 4.2.30 on 2026-06-19 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fines', '0004_foundation_prd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fine',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fine',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fine',
            name='police',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['violation'], name='idx_fine_violation'),
        ),
    ]
