path: D:/Year4/Project Thesis/Expert System/Project/CamTraffic/ai/dataset_10
train: images/train
val: images/val
nc: 10
names:
  0: NO_ENTRY
  1: NO_LEFT_TURN
  2: NO_RIGHT_TURN
  3: NO_U_TURN
  4: NO_PARKING
  5: M_STOP
  6: P_SPEED_LIMIT_20_KM_H
  7: P_SPEED_LIMIT_50_KM_H
  8: W_PEDESTRIAN_CROSSING
  9: I_ONE_WAY_TRAFFIC
