# Generated by Django 4.2.13 on 2026-05-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_signs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsign',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trafficsign',
            name='guidance_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trafficsign',
            name='sign_name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trafficsign',
            name='sign_name_km',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
