# Generated by Django 5.1.7 on 2026-07-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_models", "0001_initial"),
        ("cameras", "0001_initial"),
        ("traffic_signs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confidence", models.FloatField()),
                ("plate_number", models.CharField(blank=True, max_length=20)),
                ("plate_confidence", models.FloatField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="detections/")),
                ("bounding_box", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("detected_at", models.DateTimeField()),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detections",
                        to="cameras.camera",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detections",
                        to="ai_models.aimodelversion",
                    ),
                ),
                (
                    "traffic_sign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detections",
                        to="traffic_signs.trafficsign",
                    ),
                ),
            ],
            options={
                "db_table": "detections_detection",
                "ordering": ["-detected_at"],
            },
        ),
    ]
