# Generated by Django 4.2.30 on 2026-06-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_foundation_prd'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aimodelversion',
            index=models.Index(fields=['is_active'], name='idx_aimodel_active'),
        ),
    ]
