# Generated by Django 4.2.30 on 2026-06-19 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_foundation_prd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelversion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='aimodelversion',
            index=models.Index(fields=['is_active'], name='idx_aimodel_active'),
        ),
    ]
