# Generated by Django 4.2.30 on 2026-07-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_push_and_sms"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="idx_notif_user_read_created",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="idx_notif_type_created",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="related_object_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="related_object_type",
        ),
        migrations.AddField(
            model_name="notification",
            name="appeal_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="fine_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="link_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="violation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("fine", "Fine Issued"),
                    ("violation", "Violation Detected"),
                    ("detection", "AI Detection"),
                    ("appeal", "Appeal Update"),
                    ("payment", "Payment Confirmation"),
                    ("system", "System Message"),
                    ("alert", "Alert"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_notif_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "is_read"], name="idx_notif_user_read"),
        ),
    ]
