# Generated by Django 4.2.30 on 2026-07-24 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "notifications",
            "0005_remove_notification_idx_notif_user_read_created_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "notification_type",
                    models.CharField(default="system", max_length=20),
                ),
                ("channels", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_templates",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("enforcement_summary", "Enforcement summary"),
                            ("fines_monthly", "Fines monthly"),
                            ("violations_monthly", "Violations monthly"),
                        ],
                        default="enforcement_summary",
                        max_length=40,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("csv", "CSV"), ("xlsx", "Excel")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("recipient_emails", models.JSONField(blank=True, default=list)),
                ("run_at", models.DateTimeField()),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=40)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_reports_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_reports",
                "ordering": ["run_at"],
                "indexes": [
                    models.Index(
                        fields=["enabled", "run_at"], name="idx_sched_report_due"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduledNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                (
                    "recipient_role",
                    models.CharField(
                        choices=[
                            ("driver", "Drivers"),
                            ("officer", "Officers"),
                            ("admin", "Admins"),
                            ("all", "All users"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("channels", models.JSONField(blank=True, default=list)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="once",
                        max_length=20,
                    ),
                ),
                ("run_at", models.DateTimeField(help_text="Next (or only) run time")),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=40)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_notifications_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_notifications",
                "ordering": ["run_at"],
                "indexes": [
                    models.Index(
                        fields=["enabled", "run_at"], name="idx_sched_notif_due"
                    )
                ],
            },
        ),
    ]
