# Generated by Django 4.2.13 on 2026-05-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver_officer_alter_user_managers_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='chassis_no',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='users.driver'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_no',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner'], name='idx_vehicle_owner'),
        ),
    ]
