# Generated by Django 4.2.30 on 2026-06-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_chassis_no_vehicle_driver_vehicle_engine_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/registration/'),
        ),
    ]
