# Generated by Django 5.1.7 on 2026-07-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("detections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_text", models.CharField(max_length=100)),
                ("confidence", models.FloatField()),
                ("language", models.CharField(default="en", max_length=10)),
                ("bounding_box", models.JSONField(blank=True, default=dict)),
                (
                    "detection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_result",
                        to="detections.detection",
                    ),
                ),
            ],
            options={
                "db_table": "ocr_result",
            },
        ),
    ]
