# Generated by Django 4.2.30 on 2026-07-21 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("users", "Users"),
                            ("vehicles", "Vehicles"),
                            ("signs", "Traffic Signs"),
                            ("cameras", "Cameras"),
                            ("violations", "Violations"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending validation"),
                            ("validated", "Validated"),
                            ("committed", "Committed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("rows_report", models.JSONField(blank=True, default=list)),
                ("error_summary", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "import_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["import_type", "status"], name="idx_import_type_status"
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="idx_import_by_created",
                    ),
                ],
            },
        ),
    ]
