# Generated by Django 4.2.13 on 2026-05-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=150)),
                ('sign_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('guidance', models.TextField(blank=True, help_text='Traffic rule guidance for drivers')),
                ('image', models.ImageField(blank=True, null=True, upload_to='signs/')),
                ('category', models.CharField(choices=[('warning', 'Warning'), ('prohibitory', 'Prohibitory'), ('mandatory', 'Mandatory'), ('informative', 'Informative')], default='warning', max_length=20)),
                ('penalty', models.CharField(blank=True, max_length=255)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'traffic_signs',
                'ordering': ['category', 'sign_name'],
            },
        ),
    ]
