# Generated by Django 4.2.30 on 2026-06-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fines', '0004_foundation_prd'),
        ('violations', '0003_evidence_snapshots'),
        ('users', '0006_foundation_prd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='appeals/evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('upheld', 'Upheld'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('officer_comments', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='users.driver')),
                ('fine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='fines.fine')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_reviewed', to='users.officer')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='violations.trafficviolation')),
            ],
            options={
                'db_table': 'violation_appeals',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='idx_appeal_status_submitted'), models.Index(fields=['driver', 'status'], name='idx_appeal_driver_status')],
            },
        ),
    ]
