import type { User, Vehicle, TrafficSign, Fine, AIDetectionLog, Notification, DashboardStats } from '../types';

export const MOCK_CREDENTIALS = [
  { email: 'admin@traffic.kh', password: 'Admin@123', userId: 1 },
  { email: 'dara.chan@police.gov.kh', password: 'Police@123', userId: 2 },
  { email: 'srey.neang@police.gov.kh', password: 'Police@123', userId: 3 },
  { email: 'kosal.pich@gmail.com', password: 'Driver@123', userId: 4 },
  { email: 'vanna.sok@gmail.com', password: 'Driver@123', userId: 5 },
];

export const mockUsers: User[] = [
  {
    id: 1,
    full_name: 'Admin System',
    email: 'admin@traffic.kh',
    role: 'admin',
    phone: '+855 12 345 678',
    address: 'Ministry of Interior, Phnom Penh',
    created_at: '2024-01-01T08:00:00Z',
    is_active: true,
  },
  {
    id: 2,
    full_name: 'Dara Chan',
    email: 'dara.chan@police.gov.kh',
    role: 'police',
    phone: '+855 12 111 222',
    address: 'Traffic Police Unit, Toul Kork, Phnom Penh',
    created_at: '2024-01-15T08:00:00Z',
    is_active: true,
  },
  {
    id: 3,
    full_name: 'Srey Neang',
    email: 'srey.neang@police.gov.kh',
    role: 'police',
    phone: '+855 17 333 444',
    address: 'Traffic Police Unit, Chamkar Mon, Phnom Penh',
    created_at: '2024-01-20T08:00:00Z',
    is_active: true,
  },
  {
    id: 4,
    full_name: 'Kosal Pich',
    email: 'kosal.pich@gmail.com',
    role: 'driver',
    phone: '+855 16 555 666',
    address: 'Sen Sok, Phnom Penh',
    license_no: 'DL-KH-2024-001234',
    created_at: '2024-02-01T08:00:00Z',
    is_active: true,
  },
  {
    id: 5,
    full_name: 'Vanna Sok',
    email: 'vanna.sok@gmail.com',
    role: 'driver',
    phone: '+855 77 777 888',
    address: 'Russei Keo, Phnom Penh',
    license_no: 'DL-KH-2024-002345',
    created_at: '2024-02-10T08:00:00Z',
    is_active: true,
  },
  {
    id: 6,
    full_name: 'Pisey Mao',
    email: 'pisey.mao@gmail.com',
    role: 'driver',
    phone: '+855 89 999 000',
    address: 'Daun Penh, Phnom Penh',
    license_no: 'DL-KH-2024-003456',
    created_at: '2024-02-15T08:00:00Z',
    is_active: true,
  },
  {
    id: 7,
    full_name: 'Ratana Heng',
    email: 'ratana.heng@gmail.com',
    role: 'driver',
    phone: '+855 95 000 111',
    address: 'Meanchey, Phnom Penh',
    license_no: 'DL-KH-2024-004567',
    created_at: '2024-03-01T08:00:00Z',
    is_active: true,
  },
  {
    id: 8,
    full_name: 'Sokha Lim',
    email: 'sokha.lim@gmail.com',
    role: 'driver',
    phone: '+855 68 222 333',
    address: 'Prek Pnov, Phnom Penh',
    license_no: 'DL-KH-2024-005678',
    created_at: '2024-03-10T08:00:00Z',
    is_active: false,
  },
  {
    id: 9,
    full_name: 'Bora Keo',
    email: 'bora.keo@police.gov.kh',
    role: 'police',
    phone: '+855 98 444 555',
    address: 'Por Sen Chey, Phnom Penh',
    created_at: '2024-03-15T08:00:00Z',
    is_active: true,
  },
  {
    id: 10,
    full_name: 'Chenda Ros',
    email: 'chenda.ros@gmail.com',
    role: 'driver',
    phone: '+855 71 666 777',
    address: 'Tuol Sangke, Phnom Penh',
    license_no: 'DL-KH-2024-006789',
    created_at: '2024-03-20T08:00:00Z',
    is_active: true,
  },
];

export const mockVehicles: Vehicle[] = [
  { id: 1, owner_id: 4, owner_name: 'Kosal Pich', plate_number: '2AA 1234', vehicle_type: 'car', model: 'Toyota Camry 2022', color: 'Silver', year: 2022, created_at: '2024-02-05T08:00:00Z' },
  { id: 2, owner_id: 4, owner_name: 'Kosal Pich', plate_number: '3BB 5678', vehicle_type: 'motorcycle', model: 'Honda Wave 125', color: 'Black', year: 2021, created_at: '2024-02-05T08:00:00Z' },
  { id: 3, owner_id: 5, owner_name: 'Vanna Sok', plate_number: '1CC 9012', vehicle_type: 'car', model: 'Lexus RX350 2023', color: 'White', year: 2023, created_at: '2024-02-12T08:00:00Z' },
  { id: 4, owner_id: 6, owner_name: 'Pisey Mao', plate_number: '4DD 3456', vehicle_type: 'tuk-tuk', model: 'Electric Tuk-Tuk', color: 'Blue', year: 2022, created_at: '2024-02-20T08:00:00Z' },
  { id: 5, owner_id: 7, owner_name: 'Ratana Heng', plate_number: '2EE 7890', vehicle_type: 'motorcycle', model: 'Yamaha Exciter 155', color: 'Red', year: 2023, created_at: '2024-03-05T08:00:00Z' },
  { id: 6, owner_id: 10, owner_name: 'Chenda Ros', plate_number: '3FF 2345', vehicle_type: 'car', model: 'Hyundai Tucson 2021', color: 'Dark Grey', year: 2021, created_at: '2024-03-25T08:00:00Z' },
  { id: 7, owner_id: 5, owner_name: 'Vanna Sok', plate_number: '5GG 6789', vehicle_type: 'motorcycle', model: 'Kawasaki Z400', color: 'Green', year: 2022, created_at: '2024-04-01T08:00:00Z' },
];

export const mockTrafficSigns: TrafficSign[] = [
  {
    id: 1, sign_name: 'Stop', sign_code: 'R-01', category: 'prohibitory', image: '',
    description: 'Drivers must come to a complete stop at the marked stop line or before entering the intersection.',
    penalty: 'Fine: $25 USD | 3 demerit points',
    rules: ['Come to a complete stop', 'Wait for the way to be clear', 'Proceed only when safe', 'Do not roll through — full stop required'],
  },
  {
    id: 2, sign_name: 'No Entry', sign_code: 'R-02', category: 'prohibitory', image: '',
    description: 'Vehicles are strictly prohibited from entering this road or lane in the indicated direction.',
    penalty: 'Fine: $50 USD | 5 demerit points',
    rules: ['Do not enter the road or lane', 'Find an alternative route', 'Applies to all motor vehicles'],
  },
  {
    id: 3, sign_name: 'No Parking', sign_code: 'R-03', category: 'prohibitory', image: '',
    description: 'Parking is prohibited in this area at all times.',
    penalty: 'Fine: $15 USD | Vehicle may be towed',
    rules: ['Do not park your vehicle here', 'Vehicle may be towed at owner\'s expense', 'Applies 24 hours unless stated otherwise'],
  },
  {
    id: 4, sign_name: 'Speed Limit 40', sign_code: 'R-04', category: 'mandatory', image: '',
    description: 'Maximum speed limit is 40 kilometers per hour in this zone.',
    penalty: 'Fine: $30–$100 USD based on excess speed',
    rules: ['Do not exceed 40 km/h', 'Reduce speed in bad weather', 'School zone speed applies 7am–6pm'],
  },
  {
    id: 5, sign_name: 'Speed Limit 60', sign_code: 'R-05', category: 'mandatory', image: '',
    description: 'Maximum speed limit is 60 kilometers per hour on this road.',
    penalty: 'Fine: $30–$100 USD based on excess speed',
    rules: ['Maintain speed at or below 60 km/h', 'Reduce speed in wet conditions', 'Speed cameras may be active'],
  },
  {
    id: 16, sign_name: 'No Left Turn (R1-01)', sign_code: 'R1-01', category: 'prohibitory', image: '',
    description:
      'R1-01 — ហាមបត់ឆ្វេង (No Left Turn). Left-turn arrow crossed by red slash. All vehicles prohibited from turning left.',
    penalty: 'Fine per traffic law for illegal turn',
    rules: ['Do not turn left', 'Continue straight or turn right only', 'Used at dangerous intersections'],
  },
  {
    id: 6, sign_name: 'No U-Turn', sign_code: 'R-06', category: 'prohibitory', image: '',
    description: 'Making a U-turn is prohibited at this location.',
    penalty: 'Fine: $20 USD | 2 demerit points',
    rules: ['Do not make a U-turn here', 'Look for the next legal turning point'],
  },
  {
    id: 7, sign_name: 'Give Way (Yield)', sign_code: 'R-07', category: 'prohibitory', image: '',
    description: 'Give way to traffic on the road you are entering. Slow down and be prepared to stop.',
    penalty: 'Fine: $25 USD if failing to yield',
    rules: ['Slow down when approaching', 'Give way to all traffic on the main road', 'Be prepared to stop completely'],
  },
  {
    id: 8, sign_name: 'Pedestrian Crossing', sign_code: 'W-01', category: 'warning', image: '',
    description: 'Warning: pedestrian crossing ahead. Slow down and watch for pedestrians.',
    penalty: 'Fine: $100 USD if failing to stop for pedestrians',
    rules: ['Slow down near the crossing', 'Stop for pedestrians using the crossing', 'Do not block the crossing'],
  },
  {
    id: 9, sign_name: 'School Zone', sign_code: 'W-02', category: 'warning', image: '',
    description: 'Warning: school zone ahead. Reduce speed and watch for children.',
    penalty: 'Double fines apply in school zones',
    rules: ['Reduce speed to 30 km/h', 'Watch for children crossing', 'Active during school hours 7am–5pm'],
  },
  {
    id: 10, sign_name: 'Slippery Road', sign_code: 'W-03', category: 'warning', image: '',
    description: 'Warning: the road surface may be slippery. Reduce speed and drive with caution.',
    penalty: 'Liable for accidents caused by excessive speed',
    rules: ['Reduce speed', 'Increase following distance', 'Avoid sudden braking or steering'],
  },
  {
    id: 11, sign_name: 'One Way Street', sign_code: 'I-01', category: 'informative', image: '',
    description: 'Traffic flows in one direction only on this road.',
    penalty: 'Fine: $50 USD for driving against traffic',
    rules: ['Follow the arrow direction', 'No crossing center line', 'Wrong way driving is illegal'],
  },
  {
    id: 12, sign_name: 'Helmet Required', sign_code: 'M-01', category: 'mandatory', image: '',
    description: 'All motorcycle riders and passengers must wear an approved safety helmet.',
    penalty: 'Fine: $10 USD per person not wearing helmet',
    rules: ['Helmet must meet safety standards', 'Applies to driver and all passengers', 'Helmet must be properly fastened'],
  },
  {
    id: 13, sign_name: 'No Mobile Phone', sign_code: 'R-08', category: 'prohibitory', image: '',
    description: 'Using a mobile phone while driving is strictly prohibited.',
    penalty: 'Fine: $50 USD | 3 demerit points',
    rules: ['Do not hold phone while driving', 'Use hands-free device if needed', 'Pull over safely before using phone'],
  },
  {
    id: 14, sign_name: 'Speed Bump Ahead', sign_code: 'W-04', category: 'warning', image: '',
    description: 'Warning: speed bump or raised crosswalk ahead. Reduce speed.',
    penalty: 'Damage liability if speed not reduced',
    rules: ['Reduce speed before the bump', 'Pass over bump slowly', 'Resume normal speed after the bump'],
  },
  {
    id: 15, sign_name: 'Hospital Zone', sign_code: 'I-02', category: 'informative', image: '',
    description: 'Informational sign indicating a hospital nearby. Keep noise low.',
    penalty: 'Fine: $15 USD for excessive horn use',
    rules: ['Reduce noise levels', 'No horn unless necessary', 'Keep speed low near hospital'],
  },
];

export const mockFines: Fine[] = [
  { id: 1, driver_id: 4, driver_name: 'Kosal Pich', driver_license: 'DL-KH-2024-001234', police_id: 2, police_name: 'Dara Chan', amount: 50, reason: 'Running Red Light', status: 'paid', location: 'Monivong Blvd & Street 214, Phnom Penh', vehicle_plate: '2AA 1234', created_at: '2024-03-10T10:30:00Z', paid_at: '2024-03-12T14:00:00Z' },
  { id: 2, driver_id: 5, driver_name: 'Vanna Sok', driver_license: 'DL-KH-2024-002345', police_id: 2, police_name: 'Dara Chan', amount: 100, reason: 'Speeding (80km/h in 60km/h zone)', status: 'pending', location: 'Russian Blvd, Phnom Penh', vehicle_plate: '1CC 9012', created_at: '2024-03-15T14:20:00Z' },
  { id: 3, driver_id: 6, driver_name: 'Pisey Mao', driver_license: 'DL-KH-2024-003456', police_id: 3, police_name: 'Srey Neang', amount: 25, reason: 'No Seatbelt', status: 'paid', location: 'Norodom Blvd, Phnom Penh', vehicle_plate: '4DD 3456', created_at: '2024-03-18T09:15:00Z', paid_at: '2024-03-19T10:00:00Z' },
  { id: 4, driver_id: 7, driver_name: 'Ratana Heng', driver_license: 'DL-KH-2024-004567', police_id: 9, police_name: 'Bora Keo', amount: 10, reason: 'No Helmet (Motorcycle)', status: 'overdue', location: 'Street 271, Sen Sok, Phnom Penh', vehicle_plate: '2EE 7890', created_at: '2024-02-28T16:45:00Z' },
  { id: 5, driver_id: 10, driver_name: 'Chenda Ros', driver_license: 'DL-KH-2024-006789', police_id: 2, police_name: 'Dara Chan', amount: 50, reason: 'Wrong Way on One-Way Street', status: 'pending', location: 'Street 63, Chamkar Mon, Phnom Penh', vehicle_plate: '3FF 2345', created_at: '2024-04-01T11:30:00Z' },
  { id: 6, driver_id: 4, driver_name: 'Kosal Pich', driver_license: 'DL-KH-2024-001234', police_id: 3, police_name: 'Srey Neang', amount: 15, reason: 'Illegal Parking', status: 'paid', location: 'Near Central Market, Phnom Penh', vehicle_plate: '2AA 1234', created_at: '2024-04-05T13:00:00Z', paid_at: '2024-04-06T09:00:00Z' },
  { id: 7, driver_id: 5, driver_name: 'Vanna Sok', driver_license: 'DL-KH-2024-002345', police_id: 9, police_name: 'Bora Keo', amount: 50, reason: 'Using Mobile Phone While Driving', status: 'dismissed', location: 'Airport Road, Phnom Penh', vehicle_plate: '1CC 9012', created_at: '2024-04-08T15:45:00Z' },
  { id: 8, driver_id: 8, driver_name: 'Sokha Lim', driver_license: 'DL-KH-2024-005678', police_id: 2, police_name: 'Dara Chan', amount: 30, reason: 'Speeding in School Zone', status: 'overdue', location: 'Near Preah Sisowath HS, Phnom Penh', vehicle_plate: 'Unknown', created_at: '2024-03-05T08:30:00Z' },
  { id: 9, driver_id: 4, driver_name: 'Kosal Pich', driver_license: 'DL-KH-2024-001234', police_id: 2, police_name: 'Dara Chan', amount: 100, reason: 'Speeding (100km/h in 60km/h zone)', status: 'pending', location: 'Phnom Penh–Sihanoukville Highway', vehicle_plate: '2AA 1234', created_at: '2024-04-10T09:00:00Z' },
  { id: 10, driver_id: 7, driver_name: 'Ratana Heng', driver_license: 'DL-KH-2024-004567', police_id: 3, police_name: 'Srey Neang', amount: 25, reason: 'Failure to Stop at Stop Sign', status: 'pending', location: 'Confederation de la Russie Blvd, Phnom Penh', vehicle_plate: '2EE 7890', created_at: '2024-04-12T11:00:00Z' },
];

export const mockAILogs: AIDetectionLog[] = [
  { id: 1, user_id: 4, user_name: 'Kosal Pich', uploaded_image: 'sign_001.jpg', detected_sign: 'Stop Sign', confidence: 98.4, description: 'Octagonal red sign with white STOP text and bold border.', guidance: 'Come to a complete stop at the marked line.', created_at: '2024-04-10T10:15:00Z' },
  { id: 2, user_id: 5, user_name: 'Vanna Sok', uploaded_image: 'sign_002.jpg', detected_sign: 'No Entry', confidence: 96.2, description: 'Round red sign with horizontal white bar indicating prohibition.', guidance: 'Do not enter this road. Find an alternative route.', created_at: '2024-04-10T11:30:00Z' },
  { id: 3, user_id: 4, user_name: 'Kosal Pich', uploaded_image: 'sign_003.jpg', detected_sign: 'Speed Limit 40 km/h', confidence: 99.1, description: 'Round white sign with red border showing 40. Mandatory speed limit.', guidance: 'Reduce your speed to 40 km/h or below immediately.', created_at: '2024-04-11T09:45:00Z' },
  { id: 4, user_id: 7, user_name: 'Ratana Heng', uploaded_image: 'sign_004.jpg', detected_sign: 'Pedestrian Crossing', confidence: 94.7, description: 'Triangular yellow warning sign with walking figure.', guidance: 'Slow down and watch for pedestrians crossing ahead.', created_at: '2024-04-11T14:20:00Z' },
  { id: 5, user_id: 10, user_name: 'Chenda Ros', uploaded_image: 'sign_005.jpg', detected_sign: 'No Parking', confidence: 97.8, description: 'Round blue sign with red P crossed out.', guidance: 'Parking is not allowed here. Move to a designated zone.', created_at: '2024-04-12T16:00:00Z' },
  { id: 6, user_id: 5, user_name: 'Vanna Sok', uploaded_image: 'sign_006.jpg', detected_sign: 'School Zone', confidence: 93.9, description: 'Yellow warning sign with children crossing symbol.', guidance: 'Reduce speed to 30 km/h and watch for children.', created_at: '2024-04-13T08:30:00Z' },
];

export const mockNotifications: Notification[] = [
  { id: 1, user_id: 4, title: 'New Fine Issued', message: 'A fine of $50 USD has been issued for running a red light on March 10.', is_read: true, type: 'fine', created_at: '2024-03-10T10:35:00Z' },
  { id: 2, user_id: 4, title: 'Fine Payment Confirmed', message: 'Your payment of $50 USD (Fine #1) has been processed successfully.', is_read: true, type: 'system', created_at: '2024-03-12T14:05:00Z' },
  { id: 3, user_id: 4, title: 'New Fine Issued', message: 'A fine of $15 USD has been issued for illegal parking on April 5.', is_read: false, type: 'fine', created_at: '2024-04-05T13:05:00Z' },
  { id: 4, user_id: 4, title: 'AI Detection Complete', message: 'Traffic sign "Speed Limit 40" detected with 99.1% confidence.', is_read: false, type: 'detection', created_at: '2024-04-11T09:47:00Z' },
  { id: 5, user_id: 4, title: 'New Fine Issued', message: 'A fine of $100 USD has been issued for speeding on April 10. Pay within 30 days.', is_read: false, type: 'fine', created_at: '2024-04-10T09:05:00Z' },
  { id: 6, user_id: 5, title: 'New Fine Issued', message: 'A fine of $100 USD has been issued for speeding on March 15. Pay within 30 days.', is_read: false, type: 'fine', created_at: '2024-03-15T14:25:00Z' },
  { id: 7, user_id: 2, title: 'Monthly Report Ready', message: 'Monthly fine report for March 2024 is available. Total: 8 fines, $355 USD collected.', is_read: false, type: 'alert', created_at: '2024-04-01T08:00:00Z' },
  { id: 8, user_id: 1, title: 'AI Model Updated', message: 'AI model detection accuracy has improved to 97.2% after the latest update.', is_read: false, type: 'system', created_at: '2024-04-12T07:00:00Z' },
  { id: 9, user_id: 1, title: 'System Alert', message: 'New driver registration spike detected: 24 new accounts in the last 24 hours.', is_read: false, type: 'alert', created_at: '2024-04-13T06:30:00Z' },
];

export const mockDashboardStats: DashboardStats = {
  total_users: 248,
  total_drivers: 198,
  total_police: 45,
  total_fines: 1024,
  paid_fines: 712,
  pending_fines: 231,
  total_detections: 3456,
  total_vehicles: 312,
  fine_revenue: 48500,
  detection_accuracy: 96.8,
  monthly_fines: [
    { month: 'Jan', count: 78, revenue: 3900 },
    { month: 'Feb', count: 92, revenue: 4600 },
    { month: 'Mar', count: 104, revenue: 5200 },
    { month: 'Apr', count: 86, revenue: 4300 },
    { month: 'May', count: 95, revenue: 4750 },
    { month: 'Jun', count: 110, revenue: 5500 },
    { month: 'Jul', count: 88, revenue: 4400 },
    { month: 'Aug', count: 102, revenue: 5100 },
    { month: 'Sep', count: 97, revenue: 4850 },
    { month: 'Oct', count: 115, revenue: 5750 },
    { month: 'Nov', count: 89, revenue: 4450 },
    { month: 'Dec', count: 68, revenue: 3400 },
  ],
  monthly_detections: [
    { month: 'Jan', count: 230 }, { month: 'Feb', count: 280 }, { month: 'Mar', count: 310 },
    { month: 'Apr', count: 285 }, { month: 'May', count: 320 }, { month: 'Jun', count: 298 },
    { month: 'Jul', count: 275 }, { month: 'Aug', count: 340 }, { month: 'Sep', count: 295 },
    { month: 'Oct', count: 365 }, { month: 'Nov', count: 288 }, { month: 'Dec', count: 170 },
  ],
  fine_by_reason: [
    { reason: 'Speeding', count: 312 },
    { reason: 'Red Light', count: 245 },
    { reason: 'No Helmet', count: 198 },
    { reason: 'No Seatbelt', count: 142 },
    { reason: 'Illegal Parking', count: 89 },
    { reason: 'Wrong Way', count: 38 },
  ],
  user_distribution: [
    { role: 'Drivers', count: 198 },
    { role: 'Police', count: 45 },
    { role: 'Admin', count: 5 },
  ],
};

export const AI_DETECTION_RESULTS = [
  { detected_sign: 'Stop Sign', confidence: 98.4, description: 'Octagonal red sign with white STOP text and bold border. Regulatory sign.', guidance: 'Come to a complete stop at the marked line or before entering the intersection.' },
  { detected_sign: 'No Entry Sign', confidence: 96.2, description: 'Round red sign with horizontal white bar indicating vehicle entry prohibition.', guidance: 'Do not enter this road or lane. Find an alternative route.' },
  { detected_sign: 'Speed Limit 40 km/h', confidence: 99.1, description: 'Round white sign with red border showing "40". Mandatory maximum speed limit.', guidance: 'Reduce your speed to 40 km/h or below immediately.' },
  { detected_sign: 'Speed Limit 60 km/h', confidence: 97.8, description: 'Round white sign with red border showing "60". Mandatory maximum speed limit.', guidance: 'Maintain your speed at or below 60 km/h.' },
  { detected_sign: 'No Parking Zone', confidence: 95.3, description: 'Round blue sign with red circle and letter P crossed out by diagonal line.', guidance: 'Parking is not allowed here. Move to a designated parking area.' },
  { detected_sign: 'Pedestrian Crossing', confidence: 94.7, description: 'Triangular yellow warning sign with walking pedestrian symbol.', guidance: 'Slow down and watch for pedestrians crossing the road ahead.' },
  { detected_sign: 'School Zone Warning', confidence: 93.9, description: 'Yellow diamond sign with children crossing symbol. Active during school hours.', guidance: 'Reduce speed to 30 km/h. Extra caution for children during school hours.' },
  { detected_sign: 'Give Way (Yield)', confidence: 96.5, description: 'Inverted triangular red-bordered sign at priority intersection.', guidance: 'Slow down and give way to all traffic on the intersecting road.' },
  { detected_sign: 'No U-Turn', confidence: 97.3, description: 'Round sign with U-turn arrow crossed out in red.', guidance: 'Making a U-turn is prohibited here. Continue and find next legal turning.' },
  { detected_sign: 'One Way Street', confidence: 98.1, description: 'Rectangular blue sign with white directional arrow. One direction only.', guidance: 'Traffic flows in one direction only. Follow the arrow direction.' },
  {
    detected_sign: 'No Left Turn (R1-01)',
    confidence: 94.5,
    description:
      'R1-01 — ហាមបត់ឆ្វេង (No Left Turn). Circular sign: left-turn arrow with red prohibitory slash.',
    guidance: 'Do not turn left. Go straight or turn right where permitted.',
  },
];
