# Generated by Django 4.2.13 on 2026-05-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
        ('fines', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fine',
            name='violation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine', to='violations.trafficviolation'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['status', 'created_at'], name='idx_fine_status_created'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['driver', 'status'], name='idx_fine_driver_status'),
        ),
    ]
