# Generated by Django 4.2.30 on 2026-07-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fines", "0005_uuid_schema_alignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fine",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("awaiting_verification", "Awaiting Payment Verification"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("disputed", "Disputed"),
                    ("dismissed", "Dismissed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
