# Generated by Django 4.2.30 on 2026-07-11 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="When true, value may be exposed to authenticated non-admin clients.",
                    ),
                ),
            ],
            options={
                "verbose_name": "system setting",
                "verbose_name_plural": "system settings",
                "db_table": "system_settings",
                "ordering": ["key"],
            },
        ),
    ]
