# Generated by Django 4.2.13 on 2026-05-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='ai/uploads/')),
                ('detected_sign', models.CharField(max_length=150)),
                ('confidence', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('guidance', models.TextField(blank=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_detection_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
