# Generated by Django 4.2.13 on 2026-05-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_detection', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidetectionlog',
            name='model_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aidetectionlog',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
