# Generated by Django 4.2.13 on 2026-06-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_detection', '0005_aidetectionlog_plate_ocr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidetectionlog',
            name='plate_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='ai/evidence/plates/'),
        ),
        migrations.AddField(
            model_name='aidetectionlog',
            name='vehicle_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='ai/evidence/vehicles/'),
        ),
    ]
