# Generated by Django 4.2.30 on 2026-06-19 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_uuid_schema_alignment'),
        ('ai_detection', '0007_vehicle_tracking_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidetectionlog',
            name='matched_vehicle_id',
        ),
        migrations.AddField(
            model_name='aidetectionlog',
            name='matched_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_matches', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='aidetectionlog',
            index=models.Index(fields=['user', '-created_at'], name='idx_detection_user_created'),
        ),
        migrations.AddIndex(
            model_name='aidetectionlog',
            index=models.Index(fields=['detected_plate'], name='idx_detection_plate'),
        ),
    ]
