# Generated by Django 4.2.30 on 2026-06-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0003_foundation_prd'),
        ('infrastructure', '0003_foundation_prd'),
        ('violations', '0003_evidence_snapshots'),
        ('users', '0006_foundation_prd'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_detected', models.CharField(db_index=True, max_length=20)),
                ('violation_type', models.CharField(blank=True, max_length=30)),
                ('evidence_photo', models.ImageField(blank=True, null=True, upload_to='unknown_vehicles/evidence/')),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('officer_note', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_vehicles', to='infrastructure.camera')),
                ('linked_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_vehicle_links', to='vehicles.vehicle')),
                ('linked_violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_vehicle_sources', to='violations.trafficviolation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_vehicles_resolved', to='users.officer')),
            ],
            options={
                'db_table': 'unknown_vehicles',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['is_resolved', '-detected_at'], name='idx_unknown_resolved_detected'), models.Index(fields=['plate_detected'], name='idx_unknown_plate')],
            },
        ),
    ]
