# Generated by Django 4.2.30 on 2026-06-19 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unknown_vehicles', '0001_foundation_prd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unknownvehicle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unknownvehicle',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_vehicles_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='unknownvehicle',
            index=models.Index(fields=['camera', 'is_resolved'], name='idx_unknown_camera_resolved'),
        ),
    ]
