# Generated by Django 4.2.13 on 2026-06-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_preferences_login_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
