# Generated by Django 4.2.30 on 2026-07-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0005_phase4_officers_stations"),
        ("users", "0008_user_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="officer",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="officers",
                to="infrastructure.policestation",
            ),
        ),
    ]
