# Generated by Django 5.1.7 on 2026-07-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[("yolo", "YOLO"), ("custom", "Custom")],
                        default="yolo",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "ai_models_model",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=30)),
                ("weights_path", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("ready", "Ready"),
                            ("deprecated", "Deprecated"),
                            ("failed", "Failed"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("training_notes", models.TextField(blank=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="ai_models.aimodel",
                    ),
                ),
            ],
            options={
                "db_table": "ai_models_version",
                "ordering": ["-created_at"],
                "unique_together": {("ai_model", "version")},
            },
        ),
    ]
