# Generated by Django 4.2.13 on 2026-06-05 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sign_class_key', models.CharField(db_index=True, max_length=80)),
                ('prohibited_action', models.CharField(max_length=50)),
                ('violation_type', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('default_fine_amount', models.DecimalField(decimal_places=2, default=25, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'violation_rules',
                'ordering': ['sign_class_key', 'prohibited_action'],
            },
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='detected_class_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='detected_sign_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='observed_action',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='violation_type',
            field=models.CharField(blank=True, choices=[('ILLEGAL_LEFT_TURN', 'Illegal Left Turn'), ('ILLEGAL_RIGHT_TURN', 'Illegal Right Turn'), ('ILLEGAL_U_TURN', 'Illegal U-Turn'), ('NO_PARKING', 'No Parking'), ('NO_STOPPING', 'No Stopping'), ('ROAD_CLOSED', 'Road Closed Violation'), ('WEIGHT_LIMIT_VIOLATION', 'Weight Limit Violation')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='trafficviolation',
            index=models.Index(fields=['violation_type', 'violation_date'], name='idx_violation_type_date'),
        ),
        migrations.AddConstraint(
            model_name='violationrule',
            constraint=models.UniqueConstraint(fields=('sign_class_key', 'prohibited_action'), name='uniq_violation_rule_sign_action'),
        ),
    ]
