# Generated by Django 4.2.13 on 2026-06-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_violationrule_trafficviolation_detected_class_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficviolation',
            name='plate_evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='violations/evidence/plates/'),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='vehicle_evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='violations/evidence/vehicles/'),
        ),
    ]
