# Generated by Django 4.2.30 on 2026-07-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0004_uuid_schema_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationrule",
            name="demerit_points",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Demerit points applied to the driver license when the violation is confirmed.",
            ),
        ),
        migrations.AddField(
            model_name="violationrule",
            name="legal_reference",
            field=models.CharField(
                blank=True,
                help_text="Cambodia Land Traffic Law article / schedule reference (illustrative for thesis).",
                max_length=200,
            ),
        ),
    ]
