# Generated by Django 4.2.30 on 2026-07-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0005_cambodia_government_enforcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficviolation",
            name="violation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_ENTRY", "No Entry"),
                    ("ILLEGAL_LEFT_TURN", "Illegal Left Turn"),
                    ("ILLEGAL_RIGHT_TURN", "Illegal Right Turn"),
                    ("ILLEGAL_U_TURN", "Illegal U-Turn"),
                    ("NO_PARKING", "No Parking"),
                    ("NO_STOPPING", "No Stopping"),
                    ("ROAD_CLOSED", "Road Closed Violation"),
                    ("WEIGHT_LIMIT_VIOLATION", "Weight Limit Violation"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
