# Generated by Django 6.0.7 on 2026-07-27 17:32

from django.db import migrations, models


def backfill_rule_codes(apps, schema_editor):
    ViolationRule = apps.get_model('violations', 'ViolationRule')
    n = 1
    for rule in ViolationRule.objects.order_by('created_at', 'id'):
        rule.rule_code = f'VR{n:03d}'
        rule.save(update_fields=['rule_code'])
        n += 1


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0006_alter_trafficviolation_violation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationrule',
            name='auto_generate_fine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='violationrule',
            name='category',
            field=models.CharField(
                choices=[
                    ('traffic_sign', 'Traffic Sign'),
                    ('vehicle_behavior', 'Vehicle Behavior'),
                    ('speed', 'Speed'),
                    ('traffic_light', 'Traffic Light'),
                    ('parking', 'Parking'),
                ],
                db_index=True,
                default='traffic_sign',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name='violationrule',
            name='config',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Category-specific conditions + AI settings (confidence, OCR, review, evidence).',
            ),
        ),
        migrations.AddField(
            model_name='violationrule',
            name='detection_type',
            field=models.CharField(
                blank=True,
                default='yolo',
                help_text='yolo | ocr | fusion | manual',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name='violationrule',
            name='priority',
            field=models.PositiveSmallIntegerField(
                default=3, help_text='1 = highest priority, 5 = lowest',
            ),
        ),
        migrations.AddField(
            model_name='violationrule',
            name='rule_code',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Human-readable code e.g. VR001',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='violationrule',
            name='warning_only',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_rule_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='violationrule',
            name='rule_code',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='Human-readable code e.g. VR001',
                max_length=20,
                unique=True,
            ),
        ),
    ]
