# Generated by Django 4.2.30 on 2026-07-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0008_trafficviolation_status_closed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violationrule",
            name="category",
            field=models.CharField(
                choices=[
                    ("traffic_sign", "Traffic Sign"),
                    ("vehicle_behavior", "Vehicle Behavior"),
                    ("speed", "Speed Violation"),
                    ("traffic_light", "Traffic Light"),
                    ("parking", "Parking"),
                    ("lane_violation", "Lane Violation"),
                    ("vehicle_equipment", "Vehicle Equipment"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="traffic_sign",
                max_length=40,
            ),
        ),
    ]
