# Generated by Django 4.2.30 on 2026-06-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_foundation_prd'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='idx_audit_action_ts'),
        ),
    ]
