# Generated by Django 4.2.13 on 2026-05-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_detection', '0003_aidetectionlog_model_version_and_more'),
        ('infrastructure', '0001_initial'),
        ('vehicles', '0002_vehicle_chassis_no_vehicle_driver_vehicle_engine_no_and_more'),
        ('users', '0003_driver_officer_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='violations/evidence/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_detection_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='ai_detection.aidetectionlog')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='infrastructure.camera')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='users.driver')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations_recorded', to='users.officer')),
                ('road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='infrastructure.road')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'traffic_violations',
                'ordering': ['-violation_date'],
                'indexes': [models.Index(fields=['status', 'violation_date'], name='idx_violation_status_date'), models.Index(fields=['camera', 'violation_date'], name='idx_violation_camera_date')],
            },
        ),
    ]
