# Generated by Django 4.2.30 on 2026-06-19 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0003_evidence_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficviolation',
            name='ai_confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='bbox_coords',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='dismissal_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='officer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='plate_detected',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='road_speed_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='speed_detected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='trafficviolation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='violationrule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='trafficviolation',
            index=models.Index(fields=['driver', 'status'], name='idx_violation_driver_status'),
        ),
        migrations.AddIndex(
            model_name='trafficviolation',
            index=models.Index(fields=['plate_detected'], name='idx_violation_plate'),
        ),
    ]
