# Generated by Django 5.1.7 on 2026-07-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name_en", models.CharField(max_length=100)),
                ("name_km", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "sign categories",
                "db_table": "traffic_signs_category",
                "ordering": ["name_en"],
            },
        ),
        migrations.CreateModel(
            name="TrafficSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name_en", models.CharField(max_length=150)),
                ("name_km", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="traffic_signs/"
                    ),
                ),
                (
                    "fine_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signs",
                        to="traffic_signs.signcategory",
                    ),
                ),
            ],
            options={
                "db_table": "traffic_signs_sign",
                "ordering": ["code"],
            },
        ),
    ]
