# Generated by Django 4.2.30 on 2026-06-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_preference_muted_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='kyc_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/licenses/back/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/licenses/front/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='national_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/national_id/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('police', 'Traffic Police / Officer'), ('driver', 'Driver / Citizen')], default='driver', max_length=20),
        ),
    ]
