# Generated by Django 4.2.30 on 2026-07-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="demerit_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Accumulated demerit points under Cambodia traffic enforcement (thesis schedule).",
            ),
        ),
    ]
