# Generated by Django 6.0.7 on 2026-07-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_cambodia_government_enforcement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(fields=["-created_at"], name="idx_driver_created"),
        ),
    ]
